services:
  portfolio:
    container_name: portfolio-prod
    image: portfolio-prod
    build:
      context: ./nuxt-client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_BASE_URL=${NUXT_PUBLIC_BASE_URL}
      - NUXT_PUBLIC_STRAPI_URL=${NUXT_PUBLIC_STRAPI_URL}
    volumes:
      - /mnt/homeserver/portfolio/uploads:/opt/app/.output/public/uploads
  
  strapi:
    container_name: strapi-prod
    build: 
      context: ./api
      dockerfile: Dockerfile
    image: strapi-prod
    restart: unless-stopped
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - DATABASE_SSL=${DATABASE_SSL}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - /mnt/homeserver/portfolio/strapi-uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - default
      - supabase_default

networks:
  supabase_default:
    external: true